### ISSUE TITLE
onEndReached causes exception:

### ISSUE THREAD

**Issue by itaishalom** [flyerhq/flutter_chat_ui#284]
Hi, running on android 12, version 1.6.3.
I added onEndReached and I do a query for more messages. After 2-3 queris, I get to following exception:
(And also a progress bar is running for ever:
```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

The relevant error-causing widget was: 
  Chat Chat:file:///Users/itaishalom/AndroidStudioProjects/flutter-app3/lib/chat/ui_components/chat_inner.dart:171:32
When the exception was thrown, this was the stack: 
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:756:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:779:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2482:24)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4495:12)
#4      State.setState (package:flutter/src/widgets/framework.dart:1129:15)
#5      _ChatListState.build.<anonymous closure> (package:flutter_chat_ui/src/widgets/chat_list.dart:110:13)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3078:18)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#10     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4375:24)
#11     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#12     ScrollActivity.dispatchScrollStartNotification (package:flutter/src/widgets/scroll_activity.dart:89:65)
#13     ScrollPosition.didStartScroll (package:flutter/src/widgets/scroll_position.dart:895:15)
#14     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:887:7)
#15     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:114:11)
#16     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:7)
#17     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:157:14)
#18     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:623:15)
#19     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
#20     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:553:7)
#21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1493:20)
#22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#33     _invoke (dart:ui/hooks.dart:151:10)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#35     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderViewport#69eee NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=562.3)
...  layer: OffsetLayer#55c9c
...    engine layer: OffsetEngineLayer#5f1e1
...    handles: 2
...    offset: Offset(0.0, 0.0)
...  size: Size(384.0, 562.3)
...  axisDirection: up
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#5f60f(offset: 4001.7, range: 0.0..3985.7, viewport: 562.3, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#cc26c(AnimationController#95a28(▶ 4001.667; for BallisticScrollActivity)), ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#69eee NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=562.3)
  layer: OffsetLayer#55c9c
    engine layer: OffsetEngineLayer#5f1e1
    handles: 2
    offset: Offset(0.0, 0.0)
  size: Size(384.0, 562.3)
  axisDirection: up
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#5f60f(offset: 4001.7, range: 0.0..3985.7, viewport: 562.3, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#cc26c(AnimationController#95a28(▶ 4001.667; for BallisticScrollActivity)), ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#97164 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 64.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 4001.7, remainingPaintExtent: 562.3, crossAxisExtent: 384.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 562.3, remainingCacheExtent: 1062.3, cacheOrigin: -250.0)
...    geometry: SliverGeometry(scrollExtent: 4500.0, paintExtent: 498.3, maxPaintExtent: 4500.0, hasVisualOverflow: true, cacheExtent: 744.3)
...      scrollExtent: 4500.0
...      paintExtent: 498.3
...      maxPaintExtent: 4500.0
...      hasVisualOverflow: true
...      cacheExtent: 744.3
...    padding: EdgeInsets(0.0, 0.0, 0.0, 4.0)
...    textDirection: ltr
...    child: RenderSliverList#6fb66 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 3997.7, remainingPaintExtent: 562.3, crossAxisExtent: 384.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 562.3, remainingCacheExtent: 1062.3, cacheOrigin: -246.0)
...      geometry: SliverGeometry(scrollExtent: 4496.0, paintExtent: 498.3, maxPaintExtent: 4496.0, hasVisualOverflow: true, cacheExtent: 744.3)
...        scrollExtent: 4496.0
...        paintExtent: 498.3
...        maxPaintExtent: 4496.0
...        hasVisualOverflow: true
...        cacheExtent: 744.3
...      currently live children: 74 to 101
...      child with index 74: RenderIndexedSemantics#ad12e relayoutBoundary=up3
...        needs compositing
...        parentData: index=74; layoutOffset=3696.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 74
...        child: RenderRepaintBoundary#22051 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#394ce
...            engine layer: OffsetEngineLayer#22dd5
...            handles: 2
...            offset: Offset(0.0, 533.0)
...          size: Size(384.0, 64.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 75: RenderIndexedSemantics#06d51 relayoutBoundary=up3
...        needs compositing
...        parentData: index=75; layoutOffset=3760.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 80.0)
...        index: 75
...        child: RenderRepaintBoundary#dd2b7 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#d1685
...            engine layer: OffsetEngineLayer#7b79e
...            handles: 2
...            offset: Offset(0.0, 453.0)
...          size: Size(384.0, 80.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 76: RenderIndexedSemantics#c4c7b relayoutBoundary=up3
...        needs compositing
...        parentData: index=76; layoutOffset=3840.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 12.0)
...        index: 76
...        child: RenderRepaintBoundary#5c8ae relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#bfef7
...            engine layer: OffsetEngineLayer#6e0e4
...            handles: 2
...            offset: Offset(0.0, 441.0)
...          size: Size(384.0, 12.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 77: RenderIndexedSemantics#7b369 relayoutBoundary=up3
...        needs compositing
...        parentData: index=77; layoutOffset=3852.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 80.0)
...        index: 77
...        child: RenderRepaintBoundary#5a502 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#33fae
...            engine layer: OffsetEngineLayer#cce89
...            handles: 2
...            offset: Offset(0.0, 361.0)
...          size: Size(384.0, 80.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 78: RenderIndexedSemantics#c21de relayoutBoundary=up3
...        needs compositing
...        parentData: index=78; layoutOffset=3932.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 12.0)
...        index: 78
...        child: RenderRepaintBoundary#95c90 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#6f95e
...            engine layer: OffsetEngineLayer#be092
...            handles: 2
...            offset: Offset(0.0, 349.0)
...          size: Size(384.0, 12.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 79: RenderIndexedSemantics#a319f relayoutBoundary=up3
...        needs compositing
...        parentData: index=79; layoutOffset=3944.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 79
...        child: RenderRepaintBoundary#54c00 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#1536c
...            engine layer: OffsetEngineLayer#9439a
...            handles: 2
...            offset: Offset(0.0, 285.0)
...          size: Size(384.0, 64.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 80: RenderIndexedSemantics#dd697 relayoutBoundary=up3
...        needs compositing
...        parentData: index=80; layoutOffset=4008.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 80
...        child: RenderRepaintBoundary#ba6ec relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#8efe4
...            engine layer: OffsetEngineLayer#b0d19
...            handles: 2
...            offset: Offset(0.0, 221.0)
...          size: Size(384.0, 64.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 81: RenderIndexedSemantics#c06a7 relayoutBoundary=up3
...        needs compositing
...        parentData: index=81; layoutOffset=4072.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 81
...        child: RenderRepaintBoundary#fd19c relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#81400
...            engine layer: OffsetEngineLayer#067f7
...            handles: 2
...            offset: Offset(0.0, 157.0)
...          size: Size(384.0, 64.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 82: RenderIndexedSemantics#b2e87 relayoutBoundary=up3
...        needs compositing
...        parentData: index=82; layoutOffset=4136.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 82
...        child: RenderRepaintBoundary#97e16 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#506e7
...            engine layer: OffsetEngineLayer#58127
...            handles: 2
...            offset: Offset(0.0, 93.0)
...          size: Size(384.0, 64.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 83: RenderIndexedSemantics#b2f58 relayoutBoundary=up3
...        needs compositing
...        parentData: index=83; layoutOffset=4200.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 80.0)
...        index: 83
...        child: RenderRepaintBoundary#eb8fd relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#76948
...            engine layer: OffsetEngineLayer#9e8c5
...            handles: 2
...            offset: Offset(0.0, 13.0)
...          size: Size(384.0, 80.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 84: RenderIndexedSemantics#abeab relayoutBoundary=up3
...        needs compositing
...        parentData: index=84; layoutOffset=4280.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 12.0)
...        index: 84
...        child: RenderRepaintBoundary#9959d relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#7be42
...            engine layer: OffsetEngineLayer#7fa54
...            handles: 2
...            offset: Offset(0.0, 1.0)
...          size: Size(384.0, 12.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 85: RenderIndexedSemantics#fda8c relayoutBoundary=up3
...        needs compositing
...        parentData: index=85; layoutOffset=4292.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 80.0)
...        index: 85
...        child: RenderRepaintBoundary#174b6 relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          layer: OffsetLayer#5fc29
...            engine layer: OffsetEngineLayer#a15b7
...            handles: 2
...            offset: Offset(0.0, -79.0)
...          size: Size(384.0, 80.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child with index 86: RenderIndexedSemantics#56c06 relayoutBoundary=up3 NEEDS-PAINT
...        needs compositing
...        parentData: index=86; layoutOffset=4372.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 12.0)
...        index: 86
...        child: RenderRepaintBoundary#249d4 relayoutBoundary=up4 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 12.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 87: RenderIndexedSemantics#7d2a5 relayoutBoundary=up3 NEEDS-PAINT
...        needs compositing
...        parentData: index=87; layoutOffset=4384.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 64.0)
...        index: 87
...        child: RenderRepaintBoundary#3e6f7 relayoutBoundary=up4 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 64.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 88: RenderIndexedSemantics#22da9 relayoutBoundary=up3 NEEDS-PAINT
...        needs compositing
...        parentData: index=88; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 88
...        child: RenderRepaintBoundary#5cc6c relayoutBoundary=up4 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 89: RenderIndexedSemantics#148f0 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=89; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 89
...        child: RenderRepaintBoundary#911bd relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 90: RenderIndexedSemantics#c5e84 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=90; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 90
...        child: RenderRepaintBoundary#b6505 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 91: RenderIndexedSemantics#41f86 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=91; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 91
...        child: RenderRepaintBoundary#78ae2 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 92: RenderIndexedSemantics#bdffb relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=92; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 92
...        child: RenderRepaintBoundary#a38cf relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 93: RenderIndexedSemantics#7ea81 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=93; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 93
...        child: RenderRepaintBoundary#b702e relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 94: RenderIndexedSemantics#4f9d5 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=94; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 94
...        child: RenderRepaintBoundary#de6a7 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 95: RenderIndexedSemantics#ae411 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=95; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 95
...        child: RenderRepaintBoundary#c4adc relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 96: RenderIndexedSemantics#410fe relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=96; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 96
...        child: RenderRepaintBoundary#56080 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 97: RenderIndexedSemantics#0cbec relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=97; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 97
...        child: RenderRepaintBoundary#2cbbd relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 98: RenderIndexedSemantics#e4e9b relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=98; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 98
...        child: RenderRepaintBoundary#f1e0c relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 99: RenderIndexedSemantics#5298a relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=99; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 99
...        child: RenderRepaintBoundary#89263 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 100: RenderIndexedSemantics#d8c33 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=100; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 0.0)
...        index: 100
...        child: RenderRepaintBoundary#4ca68 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 0.0)
...          usefulness ratio: no metrics collected yet (never painted)
...      child with index 101: RenderIndexedSemantics#164f5 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: index=101; layoutOffset=4448.0 (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 48.0)
...        index: 101
...        child: RenderRepaintBoundary#b1e98 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 48.0)
...          usefulness ratio: no metrics collected yet (never painted)
...  child 1: RenderSliverPadding#6063c relayoutBoundary=up1 NEEDS-PAINT
...    parentData: paintOffset=Offset(0.0, 16.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 64.0, crossAxisExtent: 384.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 562.3, remainingCacheExtent: 318.0, cacheOrigin: 0.0)
...    geometry: SliverGeometry(scrollExtent: 48.0, paintExtent: 48.0, maxPaintExtent: 48.0, cacheExtent: 48.0)
...      scrollExtent: 48.0
...      paintExtent: 48.0
...      maxPaintExtent: 48.0
...      cacheExtent: 48.0
...    padding: EdgeInsets(0.0, 16.0, 0.0, 0.0)
...    textDirection: ltr
...    child: RenderSliverToBoxAdapter#2fca0 relayoutBoundary=up2 NEEDS-PAINT
...      parentData: paintOffset=Offset(0.0, 16.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 64.0, crossAxisExtent: 384.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 562.3, remainingCacheExtent: 318.0, cacheOrigin: 0.0)
...      geometry: SliverGeometry(scrollExtent: 32.0, paintExtent: 32.0, maxPaintExtent: 32.0, cacheExtent: 32.0)
...        scrollExtent: 32.0
...        paintExtent: 32.0
...        maxPaintExtent: 32.0
...        cacheExtent: 32.0
...      child: RenderClipRect#bed55 relayoutBoundary=up3 NEEDS-PAINT
...        parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...        constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...        size: Size(384.0, 32.0)
...        child: RenderPositionedBox#04a78 relayoutBoundary=up4 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=384.0, 0.0<=h<=Infinity)
...          size: Size(384.0, 32.0)
...          alignment: AlignmentDirectional.bottomStart
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: 1.0
====================================================================================================

```

**Comment by demchenkoalex** [comment]
Ran on my Android 11 the example we have for pagination - no issues. Was this resolved? Do I need to do something here? Not sure what the factor is.

**Comment by itaishalom** [comment]
Hi @demchenkoalex 
This is quite a problematic feature.
When end reached, the callback is called multiple times, and when the threshold was the default value, after a few of endreached, the exception occurred

**Comment by demchenkoalex** [comment]
@itaishalom on end reached should not be called if used correctly - did you `await` inside until you did all operations? you [can check the code](https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/chat_list.dart#L100) - there is a state set, `_isNextPageLoading` and it is being reset only when async `onEndReached` completed - and while it is not completed, function exits before, so unless you have not async `onEndReached` or you are not awaiting until it is done - it is practically impossible for it to be called more than once.

**Comment by itaishalom** [comment]
Ok, I think I understand.
The function is async and I use await but I run a firebase operation for the query.
And I get the response from a query snapshot and add it to the messages stream.

**Comment by demchenkoalex** [comment]
so you need to make sure you only "release" `onEndReached` when you got a response and ran (if you have any) async transformations. If the code is sync after await that is fine. You can also debug that function in the lib I pointed you to in the previous message, and see if it works correctly as well - your queries should not be performed multiple times. Let me know if you thing there is a bug and you can constantly reproduce it.

**Comment by itaishalom** [comment]
Ok thanks

**Comment by demchenkoalex** [comment]
closing for now, feel free to reopen.
