### ISSUE TITLE
Chat widget blinks (and eventually crashes) when sending text with "many" loaded messages.

### ISSUE THREAD

**Issue by doris-yolabs** [flyerhq/flutter_chat_ui#371]
# General

## What bug do you experience? 🐞
If _loadMessages start with a lot of messages, scrolling or adding 1 additional message with the example app will cause the Chat widget to blink/flashes to a blank screen.  The widget will only "come back" when I send a second message.  Any scrolling after this will cause a red screen of death.

## How can it be reproduced? 🤔
1. Start with [flutter example](https://github.com/flyerhq/flutter_chat_ui/tree/main/example): 
2. Modify `lib/main.dart`'s `_loadMessages()` with this snippet:
```
  void _loadMessages() async {
    final response = await rootBundle.loadString('assets/messages.json');
    final messages = (jsonDecode(response) as List)
        .map((e) => types.Message.fromJson(e as Map<String, dynamic>))
        .toList();

    // NEW 
    final repeats = List.filled(
      10,
      messages.first.copyWith(
        id: const Uuid().v4(),
        createdAt: DateTime.now().millisecondsSinceEpoch,
      ),
    );

    setState(() {
      _messages = [...repeats, ...messages];
    });
  }
```
3. Run with debugging
4. Send 1 message and then a second one after the flash.
6. Results in this:

https://user-images.githubusercontent.com/89052021/208857109-6510d415-a442-4557-84ea-d9af7f25e8fa.mp4

## What behavior is expected? 💡
No flash to blank / crashing.

<br />

# Extras

# Additional context
These may be red herring but adding here in case it rings any bells:

1. Once it's in this state, my CPU gets fairly high as if the app is repeatedly trying to re-render.
2. I don't have the same issue if I start with the default messages and _then_ add 10 more messages in a row, so it appears to be something related to the widgets built for the initial messages.

# Stack Traces
```
#89     RenderObject.layout
package:flutter/…/rendering/object.dart:2135
#90     RenderBox.layout
package:flutter/…/rendering/box.dart:2418
#91     MultiChildLayoutDelegate.layoutChild
package:flutter/…/rendering/custom_layout.dart:171
#92     _ScaffoldLayout.performLayout
package:flutter/…/material/scaffold.dart:1055
#93     MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:240
#94     RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:410
#95     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1973
#96     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:999
#97     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:513
#98     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:884
#99     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#100    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#101    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#102    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#103    _invoke (dart:ui/hooks.dart:148:13)
#104    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#105    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
```

**Comment by doris-yolabs** [comment]
Ah! Of course i come across https://github.com/flyerhq/flutter_chat_ui/issues/349 after I submit this.  It appears to be the same bug, and I was able to workaround the error by using this instead:
```
final repeats = List.generate(
      10,
      (i) => messages.first.copyWith(
        id: const Uuid().v4(),
        createdAt: DateTime.now().millisecondsSinceEpoch,
      ),
    );

```

With this bug in mind, we found the error in our own app where Message.id was set to `""` for incoming (other users) messages.
