### ISSUE TITLE
No host specified in URI file on RoomsPage when other chat user has not profile photo

### ISSUE THREAD

**Issue by SalahAdDin** [flyerhq/flutter_chat_ui#59]
# General

## What bug do you experience? 🐞
When we come to the rooms list page and one of the users, for instance, has no a profile photo, it gives an error on console:
```shell
======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2636:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2565:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:503:13)
...
Image provider: NetworkImage("", scale: 1.0)
Image key: NetworkImage("", scale: 1.0)
====================================================================================================
```

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. Add a new user without any profile photo.
Step 2. Go to the Rooms Page.
Step 3. Look at console.

## What behavior is expected? 💡
As it happens in the Chat page, if there is no a profile photo, just put the user's name initial letter.

<br />

# Extras

## Screenshots or videos 📸
![image](https://user-images.githubusercontent.com/5034215/124122933-52377500-da7f-11eb-8835-d6ea97f59430.png)

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
// Your snippet here...
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

```yaml
  cloud_firestore: ^2.3.0
  file_picker: ^3.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
flutter: 2.2.2

  flutter_chat_ui: ^1.1.5
  flutter_firebase_chat_core: ^1.1.0
  image_picker: ^0.8.1+3
```

`flutter doctor -v` output 👇

```sh
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /opt/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/luisalaguna/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Xiaomi Redmi Note 7 (mobile) • 192.168.56.101:5555 • android-x86    • Android 10 (API 29)
    • Chrome (web)                 • chrome              • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): ...

OS version (e.g. iOS 14.5, Android 11): ...

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
@SalahAdDin please fire issues inside an appropriate repo, rooms are not a part of `chat_ui`. I will transfer this to the Firebase repo.
